name: distZip

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: distZip
    - name: Get Time
      id: getTime
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: -6
        format: 'YYYYMMDDHHmmss'
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: "Forbidden-Island-desktop-${{ steps.getTime.outputs.time }}"
        path: ./desktop/build/distributions/Forbidden-Island-desktop-1.0.zip
        retention-days: 1